#!/usr/bin/env python3
"""Import a verified SQLite snapshot into an EMPTY PostgreSQL public schema.

Cross-platform (Python + psycopg), transactional, rehearsal ONLY. Refuses
non-empty destinations and does not change the application database driver.
"""
from __future__ import annotations
import argparse
from contextlib import closing
import hashlib
import json
import os
from pathlib import Path
import sqlite3
import sys

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "apps/api"))
from env_loader import load_env_file

def qi(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'

def pg_type(value: str) -> str:
    kind = value.upper()
    if "INT" in kind:
        return "BIGINT"
    if any(x in kind for x in ("CHAR", "CLOB", "TEXT")) or not kind:
        return "TEXT"
    if "BLOB" in kind:
        return "BYTEA"
    if any(x in kind for x in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if any(x in kind for x in ("NUMERIC", "DECIMAL")):
        return "NUMERIC"
    raise ValueError(f"Unsupported SQLite type {value!r}; review before import")

def import_snapshot(snapshot: Path, dsn: str) -> dict[str, int]:
    import psycopg
    from psycopg import sql
    snapshot = snapshot.resolve()
    manifest_path = snapshot.with_suffix(snapshot.suffix + ".manifest.json")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    digest = hashlib.sha256(snapshot.read_bytes()).hexdigest()
    if manifest["sha256"] != digest:
        raise RuntimeError("Snapshot SHA256 does not match manifest")
    with closing(sqlite3.connect(f"file:{snapshot.as_posix()}?mode=ro", uri=True)) as src:
        src.row_factory = sqlite3.Row
        if src.execute("PRAGMA integrity_check").fetchone()[0] != "ok" or src.execute("PRAGMA foreign_key_check").fetchall():
            raise RuntimeError("Invalid SQLite snapshot")
        names = [r[0] for r in src.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")]
        if set(names) != set(manifest["table_counts"]):
            raise RuntimeError("Snapshot tables differ from manifest")
        with psycopg.connect(dsn) as pg:
            with pg.cursor() as cur:
                cur.execute("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE'")
                if cur.fetchone()[0]:
                    raise RuntimeError("PostgreSQL public schema must be EMPTY; refusing import")
                foreign_keys = []
                unique_constraints = []
                generated_ids = []
                counts = {}
                for table in names:
                    columns = src.execute(f"PRAGMA table_info({qi(table)})").fetchall()
                    pks = sorted((c["pk"], c["name"]) for c in columns if c["pk"])
                    definitions = []
                    for c in columns:
                        pk_identity = len(pks) == 1 and c["name"] == "id" and c["pk"] and pg_type(c["type"]) == "BIGINT"
                        definition = f"{qi(c['name'])} {pg_type(c['type'])}"
                        if pk_identity:
                            definition += " GENERATED BY DEFAULT AS IDENTITY"
                            generated_ids.append(table)
                        if c["notnull"] or c["pk"]:
                            definition += " NOT NULL"
                        # SQLite defaults may be expressions; preserve only simple literals.
                        default = c["dflt_value"]
                        if default is not None:
                            normalized = str(default).strip()
                            if normalized.replace("-", "", 1).replace(".", "", 1).isdigit() or normalized.upper() == "NULL" or (normalized.startswith("'") and normalized.endswith("'")):
                                definition += f" DEFAULT {normalized}"
                        definitions.append(definition)
                    if pks:
                        definitions.append("PRIMARY KEY (" + ", ".join(qi(name) for _, name in pks) + ")")
                    cur.execute(f"CREATE TABLE public.{qi(table)} (" + ", ".join(definitions) + ")")
                    for fk in src.execute(f"PRAGMA foreign_key_list({qi(table)})").fetchall():
                        foreign_keys.append((table, dict(fk)))
                    for index in src.execute(f"PRAGMA index_list({qi(table)})").fetchall():
                        if index["unique"] and index["origin"] != "pk":
                            columns_idx = [v["name"] for v in src.execute(f"PRAGMA index_info({qi(index['name'])})").fetchall()]
                            if not all(columns_idx):
                                raise RuntimeError(f"Expression unique index unsupported: {index['name']}")
                            unique_constraints.append((table, index["name"], columns_idx))
                for table in names:
                    records = src.execute(f"SELECT * FROM {qi(table)}")
                    headers = [d[0] for d in records.description]
                    insert = sql.SQL("INSERT INTO public.{} ({}) VALUES ({})").format(
                        sql.Identifier(table), sql.SQL(", ").join(sql.Identifier(c) for c in headers),
                        sql.SQL(", ").join(sql.Placeholder() for _ in headers))
                    count = 0
                    for row in records:
                        cur.execute(insert, tuple(row))
                        count += 1
                    if count != manifest["table_counts"][table]:
                        raise RuntimeError(f"SQLite table changed since snapshot: {table}")
                    counts[table] = count
                for table, index_name, cols in unique_constraints:
                    cur.execute(sql.SQL("CREATE UNIQUE INDEX {} ON public.{} ({})").format(
                        sql.Identifier(index_name), sql.Identifier(table),
                        sql.SQL(", ").join(sql.Identifier(c) for c in cols)))
                # Group multi-column SQLite foreign keys by constraint ID.
                grouped = {}
                for table, fk in foreign_keys:
                    grouped.setdefault((table, fk["id"]), []).append(fk)
                for (table, fk_id), fk_rows in grouped.items():
                    fk_rows.sort(key=lambda item: item["seq"])
                    referenced = fk_rows[0]["table"]
                    from_cols = [item["from"] for item in fk_rows]
                    to_cols = [item["to"] for item in fk_rows]
                    if not all(to_cols):
                        target_keys = sorted((c["pk"], c["name"]) for c in src.execute(f"PRAGMA table_info({qi(referenced)})") if c["pk"])
                        to_cols = [name for _, name in target_keys]
                    if len(from_cols) != len(to_cols):
                        raise RuntimeError(f"Foreign key mismatch: {table} #{fk_id}")
                    # SQLite ON DELETE/UPDATE actions map to SQL keywords from trusted PRAGMA.
                    actions = {"CASCADE", "RESTRICT", "SET NULL", "SET DEFAULT", "NO ACTION"}
                    deletion = fk_rows[0]["on_delete"].upper()
                    update = fk_rows[0]["on_update"].upper()
                    if deletion not in actions or update not in actions:
                        raise RuntimeError("Unsupported foreign key action")
                    constraint = f"fk_{table}_{fk_id}"
                    cur.execute(sql.SQL("ALTER TABLE public.{} ADD CONSTRAINT {} FOREIGN KEY ({}) REFERENCES public.{} ({}) ON DELETE {} ON UPDATE {}").format(
                        sql.Identifier(table), sql.Identifier(constraint),
                        sql.SQL(", ").join(sql.Identifier(c) for c in from_cols), sql.Identifier(referenced),
                        sql.SQL(", ").join(sql.Identifier(c) for c in to_cols),
                        sql.SQL(deletion), sql.SQL(update)))
                for table in generated_ids:
                    cur.execute(sql.SQL("SELECT COALESCE(MAX(id), 0) FROM public.{}").format(sql.Identifier(table)))
                    maximum = cur.fetchone()[0]
                    cur.execute("SELECT pg_get_serial_sequence(%s, 'id')", (f"public.{qi(table)}",))
                    sequence = cur.fetchone()[0]
                    if not sequence:
                        raise RuntimeError(f"Missing ID sequence: {table}")
                    cur.execute("SELECT setval(%s, %s, %s)", (sequence, maximum if maximum else 1, bool(maximum)))
                for table, expected in counts.items():
                    cur.execute(sql.SQL("SELECT COUNT(*) FROM public.{}").format(sql.Identifier(table)))
                    if cur.fetchone()[0] != expected:
                        raise RuntimeError(f"PostgreSQL row count mismatch: {table}")
            # Leaving with-block commits only when every check passed.
        return counts

def main() -> None:
    load_env_file(ROOT / ".env")
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--snapshot", type=Path, required=True)
    ap.add_argument("--execute", action="store_true")
    args = ap.parse_args()
    if not args.snapshot.is_file():
        ap.error("Snapshot file missing")
    if not args.execute:
        print("DRY RUN: no database changes. Add --execute for import into EMPTY PostgreSQL.")
        return
    dsn = os.getenv("DATABASE_URL", "")
    if not dsn.startswith(("postgresql://", "postgres://")):
        ap.error("DATABASE_URL must target PostgreSQL")
    counts = import_snapshot(args.snapshot, dsn)
    print(f"IMPORTED: {len(counts)} tables, {sum(counts.values())} records. API STILL USES SQLITE.")

if __name__ == "__main__":
    main()
