"use client";
import { useEffect, useState } from "react";
import { api, type SessionUser } from "../lib/api";
type Overview={summary?:Record<string,number>;status_counts?:Record<string,number>};
const labels:Record<string,string>={users:"Usuários ativos",admins:"Administradores",sellers:"Representantes",companies:"Indústrias ativas",products:"Produtos ativos",customers:"Clientes ativos",associations:"Vínculos comerciais",proposals:"Pedidos e propostas",approved_orders:"Pedidos aprovados",pending_requests:"Cadastros pendentes",outbox:"Mensagens"};
const statusLabels:Record<string,string>={em_analise:"Em análise",pedido_aprovado:"Pedido aprovado",recusado:"Recusado",em_producao:"Em produção",faturado:"Faturado",entregue:"Entregue"};
const statusColors:Record<string,string>={em_analise:"bg-amber-500",pedido_aprovado:"bg-green-500",recusado:"bg-rose-500",em_producao:"bg-sky-500",faturado:"bg-indigo-500",entregue:"bg-teal-500"};
const icons:Record<string,string>={users:"♙",admins:"◆",sellers:"♧",companies:"▦",products:"◇",customers:"◉",associations:"↗",proposals:"▤",approved_orders:"✓",pending_requests:"!",outbox:"✉"};
const accents=["from-violet-50 to-white","from-blue-50 to-white","from-emerald-50 to-white","from-amber-50 to-white"];
export default function DashboardView({user}:{user:SessionUser}){
 const [data,setData]=useState<Overview|Record<string,unknown>>({}),[busy,setBusy]=useState(true),[error,setError]=useState(""),[revision,setRevision]=useState(0);
 const admin=user.role==="admin";
 useEffect(()=>{let active=true;setBusy(true);setError("");
 api<Overview|Record<string,unknown>>(admin?"/api/admin/overview":"/api/dashboard").then(v=>{if(active)setData(v)}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Falha ao consultar indicadores")}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[admin,revision]);
 const overview=data as Overview;
 const summary=overview.summary||Object.fromEntries(Object.entries(data).filter(([,v])=>typeof v==="number")) as Record<string,number>;
 const counts=overview.status_counts||{};
 const total=Object.values(counts).reduce((sum,value)=>sum+value,0);
 const entries=Object.entries(summary).filter(([,v])=>typeof v==="number");
 return <section className="space-y-6 pb-8">
 <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-violet-700">HiperMix · Gestão comercial</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">Painel executivo</h1><p className="mt-2 text-sm text-slate-500">{admin?"Acompanhe os indicadores, a operação e o desempenho da equipe.":"Acompanhe seus indicadores e a operação comercial."}</p></div><button type="button" disabled={busy} onClick={()=>setRevision(x=>x+1)} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm transition hover:border-violet-300 hover:text-violet-700 disabled:opacity-60"><span aria-hidden>↻</span> Atualizar dados</button></div>
 {error&&<div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-rose-700">{error}</div>}
 {busy?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:8},(_,i)=><div key={i} className="h-36 animate-pulse rounded-2xl bg-slate-200/70"/>)}</div>:<>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{entries.map(([key,value],i)=><article key={key} className={`relative overflow-hidden rounded-2xl border border-slate-200 bg-gradient-to-br ${accents[i%accents.length]} p-5 shadow-[0_8px_25px_rgba(30,18,65,.045)] transition hover:-translate-y-0.5 hover:shadow-lg`}><div className="flex items-start justify-between gap-2"><span className="text-sm font-semibold text-slate-600">{labels[key]||key.replaceAll("_"," ")}</span><span aria-hidden className="grid size-10 shrink-0 place-items-center rounded-xl border border-white bg-white/85 text-lg font-bold text-violet-700 shadow-sm">{icons[key]||"▥"}</span></div><p className="mt-5 text-3xl font-extrabold tracking-tight tabular-nums text-slate-950">{value.toLocaleString("pt-BR")}</p><p className="mt-2 text-xs text-slate-500">Informações atualizadas da HiperMix</p></article>)}</div>
 {total>0&&<div className="grid gap-5 xl:grid-cols-[1.4fr_1fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-[0_8px_30px_rgba(30,18,65,.04)]"><div className="mb-6"><p className="text-[11px] font-extrabold uppercase tracking-[.16em] text-violet-700">Operação</p><h2 className="mt-1 text-xl font-bold text-slate-950">Status dos pedidos</h2><p className="mt-1 text-sm text-slate-500">Distribuição dos registros por etapa comercial.</p></div><div className="space-y-5">{Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([key,val])=><div key={key}><div className="mb-2 flex items-center justify-between text-sm"><span className="font-semibold text-slate-700">{statusLabels[key]||key.replaceAll("_"," ")}</span><span className="font-bold tabular-nums text-slate-800">{val.toLocaleString("pt-BR")} <span className="font-normal text-slate-400">· {Math.round(100*val/total)}%</span></span></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full transition-all ${statusColors[key]||"bg-violet-500"}`} style={{width:`${100*val/total}%`}}/></div></div>)}</div></section><section className="flex flex-col justify-between rounded-2xl border border-violet-200 bg-gradient-to-br from-[#2e164b] to-[#522574] p-6 text-white shadow-[0_12px_30px_rgba(46,22,75,.12)]"><div><p className="text-xs font-bold uppercase tracking-[.17em] text-violet-200">Visão rápida</p><h2 className="mt-3 text-2xl font-bold">Operação comercial</h2><p className="mt-3 max-w-sm text-sm leading-6 text-violet-100">Consulte os números da operação e acompanhe a evolução dos pedidos sem sair do painel.</p></div><div className="mt-8 border-t border-white/20 pt-5"><p className="text-sm text-violet-200">Total de pedidos por etapa</p><p className="mt-1 text-4xl font-extrabold tabular-nums">{total.toLocaleString("pt-BR")}</p></div></section></div>}
 {!entries.length&&<div className="rounded-2xl border bg-white p-6 text-slate-500">Não há indicadores disponíveis.</div>}
 </>}
 </section>;
}
